logo_title: 大圣博客

style: black

favicon: /favicon.ico

menu:
    分类: /categories/js常见问题/
    标签: /tags/javascript/
    文章: /article/
    关于: /about
    Github: https://github.com/webbHou

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
    enable: true
    appId: 4QJZu2oB7BcbrCJACqhWnmt2-gzGzoHsz
    appKey: QAjplUsOViSYZJg9F7UAozl8

highlight:
    enable: true
